### ISSUE TITLE
removeBimeraDenovo issue

### ISSUE THREAD

**Issue by Jackfabo** [giovannellilab/dada2_pipeline#4]
whenever i use this line in jupyter
> seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE)

i get this error as a result

 ```
Error in isBimeraDenovoTable(unqs[[i]], ..., verbose = verbose): Input must be a valid sequence table.
Traceback:
1. removeBimeraDenovo(seqtab, method = "consensus", multithread = TRUE)
2. isBimeraDenovoTable(unqs[[i]], ..., verbose = verbose)
3. stop("Input must be a valid sequence table.")

```
this zipfile is my jupyter notebook work i hope that can help someone to figure up what i have done wrong 
[Dada 2 Pipeline example.zip](https://github.com/giovannellilab/dada2_pipeline/files/4629538/Dada.2.Pipeline.example.zip)

**Comment by MatS792** [comment]
I think the problem is in:  seqtab <- seqtab[,nchar(colnames(seqtab)) %in% seq(371,383)]
The range (371,383) is an example coming from another analysis with a different dataset. On the pipeline, above the command, it is suggested to change the seq numbers within brackets to **match** the min and max length **desired**. In your specific case, you don't need to choose a length distribution to keep because you have only one value as result of the command: table(nchar(getSequences(seqtab)))
Try to jump this step and continue with the pipeline.

**Comment by Jackfabo** [comment]
i have solved putting 228-293 in the pipeline instead of 371-383.
thanks for helping me
